
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: pulsa_api
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run dev-api

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: pulsa_worker
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run dev-worker

  postgres:
    image: postgres:15
    container_name: pulsa_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serverpulsa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: pulsa_redis
    ports:
      - "6379:6379"

  mock_supplier:
    build:
      context: .
      dockerfile: Dockerfile.supplier
    container_name: pulsa_mock_supplier
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    command: node mock/supplier.js

volumes:
  postgres_data:
