# FROM node:18
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "run", "worker"]


FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install



COPY . .

CMD ["npm", "run", "dev-worker"]
